### ISSUE TITLE
Add new shape (circle)

### ISSUE THREAD

**Issue by kozintsev** [Core2D/Core2D#48]
Hello!

I liked Core2D toolkit and I want add new shape. 
I want to add a method for drawing a circle.
Could you give recommendations how to do it correctly?
First you need to choose a center, then the radius.

Best regard, Oleg

**Comment by wieslawsoltes** [comment]
@kozintsev You can start with Ellipse tool as base for Circle tool:

https://github.com/Core2D/Core2D/blob/master/src/Core2D/Editor/Tools/ToolEllipse.cs

and also check the ArcTool for how too.

After that you have to register the CircleTool in editor and add to tool menu:

https://github.com/Core2D/Core2D/search?utf8=%E2%9C%93&q=ToolEllipse

**Comment by kozintsev** [comment]
Thanks for the answer. I tried to use Elips class, but I do not like results.
How can I set the helper point in the center?

My class:

https://github.com/kozintsev/Core2D/blob/master/src/Core2D/Editor/Tools/ToolCircle.cs

**Comment by wieslawsoltes** [comment]
Check this helper for Arc tool:
https://github.com/Core2D/Core2D/blob/master/src/Core2D/Editor/Tools/Selection/ArcSelection.cs

**Comment by kozintsev** [comment]
Will need to create its shape? Although I have solved the problem using only the ellipse.
For example... Here you need to create the XCircle.cs file?
\Core2D\src\Core2D\Shapes\

**Comment by wieslawsoltes** [comment]
Yes here \Core2D\src\Core2D\Shapes\ you can add new shape objects. I would not recommend creating such shape. The idea is that you can later manipulate object points and with circle this is more difficult.

**Comment by kozintsev** [comment]
Thanks for the info.
